### ISSUE TITLE
🐛 Wrong param in method store()

### ISSUE THREAD

**Issue by gogl92** [Insolita/yii2-muffin-factory#1]
I'm getting the error:
`TypeError: Argument 1 passed to insolita\muffin\FactoryBuilder::store() must be of the type array, object given, called in /var/www/vendor/insolita/yii2-muffin-factory/src/FactoryBuilder.php on line 137`

This is because:

Method `store()` :
```
    /**
     * @param  array|ActiveRecord[] $results
     *
     * @return void
     */
    protected function store(array $results)
    {
        foreach ($results as $model) {
            $model->save(false);
        }
    }
```

Can only receive an array of results but method `create(array $attributes  = [])` make a call without an array `$this->store($results);`

I'm not sure if I'm seeing this error because I'm using mongodb, although calling the method as only array can solve the problem.

```
    public function create(array $attributes = [])
    {
        $results = $this->make($attributes);

        $this->store([$results]);

        return $results;
    }
```

**Comment by Insolita** [comment]
Try the latest version. If it doesn't solve your problem, provide an example with your db model and factory file.

**Comment by gogl92** [comment]
@Insolita 
![giphy](https://user-images.githubusercontent.com/1505641/104941521-cb7f5780-5978-11eb-8963-9872899955f7.gif)
